name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore

      - name: Test
        run: dotnet test --no-restore --configuration Release

      - name: Publish
        run: >
          dotnet publish
          src/Jellyfin.Plugin.PathHider/Jellyfin.Plugin.PathHider.csproj
          --no-restore
          --configuration Release
          --output artifacts

      - uses: actions/upload-artifact@v4
        with:
          name: Jellyfin.Plugin.PathHider
          path: artifacts/Jellyfin.Plugin.PathHider.dll
